version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: STUDENTSREPO
    ports:
      # port exposed : mysql port running inside container
      - "3306:3306"

